### ISSUE TITLE
Impossible to intialise different R values for each dimension.

### ISSUE THREAD

**Issue by nverstaevel** [nverstaevel/ciel#7]
It's not possible to assign a R value for each dimension. It's problematic when we consider machine learning problems with features of different size. 

R should be at least expressed for each of the dimentions.

**Comment by Seladus** [comment]
It's possible to assign a different R value for each input dimension:

```python
import torch
from torch_mas.head import Head

model = Head(
    4,
    1,
    R=torch.Tensor([0.1, 0.1, 3, 1]),
    imprecise_th=0.001,
    bad_th=0.01,
    alpha=0.2,
    memory_length=10,
    n_epochs=1,
    l1=0.1
)
```
